#!/usr/bin/with-contenv bash

# fixes for gnome and flatpaks
for file in $(find /usr -type f -iname "*login1*"); do rm -v $file; done
echo "\n\nexport $(dbus-launch)\nexport XDG_CURRENT_DESKTOP=GNOME\nexport XDG_DATA_DIRS=/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share:/usr/local/share:/usr/share\nexport XDG_SESSION_TYPE=x11\nexport DESKTOP_SESSION=gnome-xorg" >> /etc/profile

# start dbus
service dbus start
