#!/usr/bin/with-contenv bash

# fixes for gnome and flatpaks
for file in $(find /usr -type f -iname "*login1*"); do rm -v $file; done

# remove shortuts and panels
rm -v /usr/share/applications/gnome-network-panel.desktop \
    /usr/share/applications/gnome-sharing-panel.desktop \
    /usr/share/applications/gnome-color-panel.desktop \
    /usr/share/applications/gnome-language-selector.desktop \
    /usr/share/applications/update-manager.desktop \
    /usr/share/applications/software-properties-drivers.desktop \
    /usr/share/applications/software-properties-gtk.desktop
    

if [ ! -f "/config/.firstsetup" ]; then
    echo "\n\nexport $(dbus-launch)\nexport XDG_CURRENT_DESKTOP=GNOME\nexport XDG_DATA_DIRS=/var/lib/flatpak/exports/share:/config/.local/share/flatpak/exports/share:/usr/local/share:/usr/share\nexport XDG_SESSION_TYPE=x11\nexport DESKTOP_SESSION=gnome-xorg" >> /etc/profile

    mkdir -p /config/.config/{gtk-3.0,gtk-4.0}
    mkdir -p /config/{Desktop,Documents,Downloads,Music,Pictures,Public,Templates,Videos}
    touch /config/.firstsetup
fi

# fix permissions
chown abc:abc /config/.config/{gtk-3.0,gtk-4.0}/*
chown abc:abc /config/{Desktop,Documents,Downloads,Music,Pictures,Public,Templates,Videos}

# start dbus
service dbus start
