---
services:
  webtop:
    image: ghcr.io/tibor309/webtop:lubuntu
    container_name: lubuntu-webtop
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /lubuntu-webtop:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri
    shm_size: "1gb"
    restart: unless-stopped