#!/usr/bin/with-contenv bash

if [ ! -f "/config/.config/.firstsetup" ]; then
    mkdir -p /config/.config/{gtk-3.0,gtk-4.0}
    mkdir -p /config/{Desktop,Documents,Downloads,Music,Pictures,Public,Templates,Videos}
    touch /config/.config/.firstsetup
fi

# fix permissions
chown abc:abc /config/.config/{gtk-3.0,gtk-4.0}/*
chown abc:abc /config/{Desktop,Documents,Downloads,Music,Pictures,Public,Templates,Videos}
