name: "Build Docker image"
description: "Builds a Docker image for the selected desktop environment and pushes it to the GitHub Container Registry and Docker Hub."
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select a desktop to build"
        required: true
        default: "ubuntu-cinnamon"
        type: choice
        options:
          - ubuntu
          - ubuntu-vanilla
          - ubuntu-cinnamon
          - kubuntu
          - xubuntu
          - fedora-kde
          - fedora-xfce
          - zorinos-core

permissions:
  contents: read
  packages: write

jobs:
  get_img_tags:
    name: Determine image tags
    runs-on: ubuntu-latest
    outputs:
      image_tags: ${{ steps.set_img_tags.outputs.TAGS }}
    steps:
      - name: Determine image tags
        id: set_img_tags
        run: |
          if [[ "${{ inputs.branch }}" == "ubuntu-cinnamon" ]]; then
            echo "TAGS=ghcr.io/tibor309/webtop:latest,ghcr.io/tibor309/webtop:ubuntu-cinnamon,tibordev/webtop:latest,tibordev/webtop:ubuntu-cinnamon" >> $GITHUB_OUTPUT
          else
            echo "TAGS=ghcr.io/tibor309/webtop:${{ inputs.branch }},tibordev/webtop:${{ inputs.branch }}" >> $GITHUB_OUTPUT
          fi
          echo "Image tag(s): $TAGS"

  get_date:
    name: Get current date in RFC 3339
    runs-on: ubuntu-latest
    outputs:
      IMG_DATE: ${{ steps.date.outputs.IMG_DATE }}
    steps:
      - name: Get current date in RFC 3339
        id: date
        run: |
          IMG_DATE=$(date --rfc-3339=seconds | sed 's/ /T/')
          echo "IMG_DATE=${IMG_DATE}" >> $GITHUB_OUTPUT
          echo "The date is $IMG_DATE"

  build_push:
    name: Build and push image
    runs-on: ubuntu-latest
    needs: [get_img_tags, get_date]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: tibor309
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: tibordev
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image for amd64/arm64
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          build-args: |
            IMAGE_BUILD_DATE=${{ needs.get_date.outputs.IMG_DATE }}
          tags: |
            ${{ needs.get_img_tags.outputs.image_tags }}
